src/activity_logger/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("BlogPost")

src/activity_logger/blog_posts/views.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from activity_logger.blog_posts.forms import BlogPostForm
from activity_logger.models.org import BlogPost, db

blog_posts = Blueprint("blog_posts", __name__)


@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post_entry = BlogPost(
            title=form.title.data, text=form.text.data, user_id=current_user.id
        )
        db.session.add(blog_post_entry)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for("core.index"))

    return render_template("create_post.html", form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post_entry = BlogPost.query.get_or_404(blog_post_id)
    return render_template(
        "blog_post.html",
        title=blog_post_entry.title,
        date=blog_post_entry.date,
        post=blog_post_entry,
    )


@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_post_entry = BlogPost.query.get_or_404(blog_post_id)
    if blog_post_entry.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post_entry.title = form.title.data
        blog_post_entry.text = form.text.data
        db.session.commit()
        flash("Post Updated")
        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post_entry.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    if request.method == "GET":
        form.title.data = blog_post_entry.title
        form.text.data = blog_post_entry.text
    return render_template("create_post.html", title="Update", form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=["POST"])
@login_required
def delete_post(blog_post_id):
    blog_post_entry = BlogPost.query.get_or_404(blog_post_id)
    if blog_post_entry.author != current_user:
        abort(403)
    db.session.delete(blog_post_entry)
    db.session.commit()
    flash("Post has been deleted")
    return redirect(url_for("core.index"))

src/activity_logger/core/views.py
from flask import Blueprint, render_template, request

from activity_logger.models.org import BlogPost

core = Blueprint("core", __name__)


@core.route("/")
def index():
    """
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    """
    page = request.args.get("page", 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template("index.html", blog_posts=blog_posts)


@core.route("/info")
def info():
    """
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    """
    return render_template("info.html")


@core.route("/dash")
def dash():
    return render_template("my_dash.html")

src/activity_logger/users/views.py
from functools import wraps

from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from activity_logger.models.db_activites import Activities, ActivityType, UnitType
from activity_logger.models.org import BlogPost, Role, User, db
from activity_logger.users.forms import (
    ActivityForm,
    LoginForm,
    RegistrationForm,
    UpdateUserForm,
)
from activity_logger.users.picture_handler import add_profile_pic

users_blueprint = Blueprint("users", __name__)


def admin_required(view_func):
    @wraps(view_func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_authenticated or str(current_user.role) != "Admin":
            abort(403)  # HTTP status code for Forbidden
        return view_func(*args, **kwargs)

    return decorated_view


@users_blueprint.route("/register", methods=["GET", "POST"])
@login_required
@admin_required
def register():
    form = RegistrationForm()

    form.role.choices = [(role.id, role.role) for role in Role.query.all()]

    if form.validate_on_submit():
        user = User(
            email=form.email.data, username=form.username.data, password=form.password.data
        )
        # user.role = Role.query.filter_by(role="Admin").first()
        user.role = Role.query.filter_by(id=form.role.data).first()
        db.session.add(user)
        db.session.commit()
        flash("Thanks for registering! Now you can login!")
        return redirect(url_for("users.login"))
    for field, errors in form.errors.items():
        for error in errors:
            flash(f'Error in field "{getattr(form, field).label.text}": {error}', "error")
    return render_template("register.html", form=form)


@users_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        if user is None:
            flash("User is not available", "error")
            return render_template("login.html", form=form)

        if not user.check_password(form.password.data):
            flash("Password is not correct", "error")
            return render_template("login.html", form=form)

        # Log in the user

        login_user(user, remember=True)

        flash("Logged in successfully.")

        # If a user was trying to visit a page that requires a login
        # flask saves that URL as 'next'.
        next = request.args.get("next")  # pylint: disable=redefined-builtin

        # So let's now check if that next exists, otherwise we'll go to
        # the welcome page.
        if next is None or not next[0] == "/":
            next = url_for("core.index")

        return redirect(next)
    for field, errors in form.errors.items():
        for error in errors:
            flash(f'Error in field "{getattr(form, field).label.text}": {error}', "error")

    return render_template("login.html", form=form)


@users_blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


@users_blueprint.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            print("Picture available")
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("User Account Updated")
        print("User Account Updated")
        return redirect(url_for("users.account"))

    if request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for("static", filename="profile_pics/" + current_user.profile_image)
    return render_template("account.html", profile_image=profile_image, form=form)


@users_blueprint.route("/test/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = (
        BlogPost.query.filter_by(author=user)
        .order_by(BlogPost.date.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_blog_posts.html", blog_posts=blog_posts, user=user)


# Define the route for the home page
@users_blueprint.route("/activities", methods=["GET", "POST"])
def activities():
    # Create an instance of the form
    form = ActivityForm()

    form.activity.choices = [
        (activity.id, activity.activity_type) for activity in ActivityType.query.all()
    ]
    form.unit.choices = [(unit.id, unit.unit_type) for unit in UnitType.query.all()]

    # Check if the form is validated on submission
    if form.validate_on_submit():
        # Get the data from the form fields
        activity = form.activity.data
        time = form.time.data
        value = form.value.data
        unit = form.unit.data

        my_unit = UnitType.query.filter_by(id=unit).first()
        my_activity = ActivityType.query.filter_by(id=activity).first()

        activity_to_save = Activities(
            my_activity=my_activity, value=value, my_unit=my_unit, my_user=current_user
        )

        db.session.add(activity_to_save)
        db.session.commit()
        # Redirect to the result page with the data as query parameters
        return redirect(
            url_for("users.result", activity=activity, time=time, value=value, unit=unit)
        )
    for field, errors in form.errors.items():
        for error in errors:
            flash(f'Error in field "{getattr(form, field).label.text}": {error}', "error")
    # Render the template with the form as an argument
    return render_template("activities.html", form=form)


# Define the route for the result page
@users_blueprint.route("/result", methods=["GET", "POST"])
def result():
    # Get the data from the query parameters
    activity = request.args.get("activity")
    time = request.args.get("time")
    value = request.args.get("value")
    unit = request.args.get("unit")
    # Render the template with the data as arguments
    return render_template("result.html", activity=activity, time=time, value=value, unit=unit)


@users_blueprint.route("/flash", methods=["GET", "POST"])
def my_flash():
    # Defined in base.html (Flash)
    flash("Should be an error", "error")
    flash("Should be an info")
    return redirect(url_for("core.index"))

src/activity_logger/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

src/activity_logger/templates/activities.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="text-center">Log your Activities</h1>
    <p class="text-center">Here you can log your activities</p>
    <!-- Display the form using the form argument -->
    <form method="POST" class="row g-3">
        {{ form.hidden_tag() }}
        <div class="col-md-6">
            <label for="{{ form.activity.id }}" class="form-label">{{ form.activity.label }}</label>
            {{ form.activity(class="form-select") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.time.id }}" class="form-label">{{ form.time.label }}</label>
            {{ form.time(class="form-control") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.value.id }}" class="form-label">{{ form.value.label }}</label>
            {{ form.value(class="form-control") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.unit.id }}" class="form-label">{{ form.unit.label }}</label>
            {{ form.unit(class="form-select") }}
        </div>
        <div class="col-12">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

src/activity_logger/templates/base.html
<!DOCTYPE html>
<html>

<head>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700;900&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
        integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link rel="stylesheet" href="static/master.css">
    <meta charset="utf-8">
    <title></title>
</head>

<body data-bs-spy="scroll" data-bs-target=#main_menu>
    <!-- Header Area -->
    <header id="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top">
            <div class="container">
                <!-- Logo -->
                <a href="" class="navbar-brand"><img src="static/logo.jpg" alt=""></a>

                <!-- Mobile Menu Icon -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainmenu"><span
                        class="navbar-toggler-icon"></span></button>

                <!-- Main Menu  -->
                <div id="mainmenu" class="collapse navbar-collapse">
                    <ul class="navbar-nav ms-auto">
                        <li><a class="nav-link" href="{{ url_for('core.index') }}">Home</a></li>
                        <li><a class="nav-link" href="#about">About</a></li>
                        <li><a class="nav-link" href="#contact">Contact us</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('core.dash') }}">Dash</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.activities') }}">Activities</a>
                        </li>
                        {% if current_user.is_authenticated %}
                        {% if current_user.role_id == 1 %}
                        <li class="nav-item"><a class="nav-link" href="./admin">My Admin</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                        </li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
                        <li class="nav-item">
                            <a class="nav-link disabled"><i class="bi bi-person-circle"></i> {{ current_user.username
                                }}</a>
                        </li>

                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Log In</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- ************************************* -->
    <!-- Flash -->
    <!-- ************************************* -->

    <div class="section" id="first_section">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul>
            {% for category, message in messages %}
            <div class="col-md-8 offset-md-2">
                {% if category == 'error' %}
                <div class="alert alert-danger" role="alert">
                    <li class="list-group-item">{{ message }}</li>
                </div>
                {% else %}
                <div class="alert alert-dark" role="alert">
                    <li class="list-group-item">{{ message }}</li>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
    </div>

    {% block content %}

    {% endblock %}
    </div>

    <script src="static/js/bootstrap.min.js"></script>
</body>

</html>

src/activity_logger/templates/blog.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome to the activity page</h1>
    <p>Please add you activities</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

src/activity_logger/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

src/activity_logger/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

src/activity_logger/templates/index.html
{% extends "base.html" %}
{% block content %}
<!-- Slider Area -->
<section id="slider" class="carousel slide carousel-dark carousel-fade" data-,cbs-ride="carousel" data-bs-touch="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#slider" data-bs-slide-to="0" class="active" aria-current="true"
            aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#slider" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#slider" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active text-center">
            <img src="static/banner1.jpg" alt="" class="d-block mx-auto">
        </div>
        <div class="carousel-item text-center">
            <img src="static/banner2.jpg" alt="" class="d-block mx-auto">
        </div>
        <div class="carousel-item text-center">
            <img src="static/banner3.jpg" alt="" class="d-block mx-auto">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#slider" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#slider" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
    </button>
</section>


<!-- About Area -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-6 align-self-center">
                <h2>About Us</h2>
                <h6>What We Do?</h6>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat, ipsam culpa. Commodi aspernatur
                    temporibus placeat libero fugit at sequi consequuntur.</p>
                <button class="btn btn-info">Learn More</button>
            </div>
            <div class="col-md-6">
                <img src="img/about.jpg" alt="">
            </div>
        </div>
    </div>
</section>

<!-- Contact Area -->
<section id="contact" class="pb-md-5 pb-3">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card p-4 text-center">
                    <h2>Contact Us</h2>
                    <p>If you have any suggestion, just write us!</p>
                    <form action="" class="mt-3 text-start">
                        <label for="" class="form-label">Your Name</label>
                        <input type="em" name="" id="" placeholder="Enter Your Name" class="form-control mb-2">
                        <label for="" class="form-label">Your Email</label>
                        <input type="email" name="" id="" placeholder="Enter Your Email" class="form-control mb-2">
                        <label for="" class="form-label">Your Phone</label>
                        <input type="text" name="" id="" placeholder="Enter Your Phone Number"
                            class="form-control mb-2">
                        <label for="" class="form-label">Your Subject</label>
                        <input type="text" name="" id="" placeholder="Enter Your Subject" class="form-control mb-2">
                        <label for="" class="form-label">Your Message</label>
                        <textarea name="" id="" cols="30" rows="10" placeholder="Enter your Message"
                            class="form-control mb-2"></textarea>
                        <input type="submit" value="Send Message" class="btn btn-info">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

src/activity_logger/templates/info.html
{% extends "base.html" %}
{% block content %}
{% if current_user.is_authenticated %}
  Hi {{ current_user.username }}!
{% endif %}

{% endblock %}

src/activity_logger/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="section" id="first_section">

<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>

</div>


{% endblock %}

src/activity_logger/templates/my_dash.html
{% extends "base.html" %}
{% block content %}

<iframe src="./dashapp" width="100%" height="500"></iframe>


{% endblock %}

src/activity_logger/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form method="POST" class="row g-3">
        {{ form.hidden_tag() }}
        <div class="col-md-6">
            <label for="{{ form.role.id }}" class="form-label">{{ form.role.label }}</label>
            {{ form.role(class="form-select") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.email.id }}" class="form-label">{{ form.email.label }}</label>
            {{ form.email(class="form-control") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.username.id }}" class="form-label">{{ form.username.label }}</label>
            {{ form.username(class="form-control") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.password.id }}" class="form-label">{{ form.password.label }}</label>
            {{ form.password(class="form-control") }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.pass_confirm.id }}" class="form-label">{{ form.pass_confirm.label }}</label>
            {{ form.pass_confirm(class="form-select") }}
        </div>
        <div class="col-12">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

src/activity_logger/templates/result.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="text-center">Flask-WTF Example</h1>
    <p class="text-center">This is the result of your input.</p>
    <!-- Display the data using the arguments passed from the route function -->
    <div class="card">
        <div class="card-body">
            <p class="card-text">You chose {{ activity }} as your activity.</p>
            <p class="card-text">You did your activity on {{ time }}.</p>
            <p class="card-text">You entered {{ value }} {{ unit }} as your value.</p>
        </div>
    </div>
</div>
{% endblock %}

src/activity_logger/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}